version: "3.7"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  test-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "54321:5432" # Use a different port to avoid conflicts with the main database
    expose:
      - "54321" # Exposing the different port for clarity
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/backend/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    env_file:
      - .env
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"

volumes:
  db-data:
  test-db-data:
