version: "3.7"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../server/.env
    ports:
      - "54320:5432"
    expose:
      - "54320"
    volumes:
      - ../.db-data:/var/lib/postgresql/data:cached

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    command: ["./server"]
    tty: true
    env_file:
      - ../server/.env
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - . :/tg_bot/:cached
    env_file:
      - ../server/.env
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
